# Generated by Django 3.2.9 on 2021-12-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_q', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.ladder')),
            ],
        ),
    ]
