# Generated by Django 3.2.9 on 2021-12-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladder',
            name='total_q',
            field=models.IntegerField(default=0),
        ),
    ]
