# Generated by Django 3.2.9 on 2021-12-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_ladder_total_q'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
    ]
