# Generated by Django 3.2.9 on 2021-12-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_problems_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='pid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
