# Generated by Django 3.2.7 on 2021-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('codechef_handle', models.CharField(max_length=50)),
                ('codeforces_handle', models.CharField(max_length=50)),
                ('atcoder_handle', models.CharField(max_length=50)),
                ('num_ques', models.IntegerField(default=0)),
            ],
        ),
    ]
