# Generated by Django 3.2.7 on 2021-12-04 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codechef_handle', models.CharField(max_length=50)),
                ('codeforces_handle', models.CharField(max_length=50)),
                ('atcoder_handle', models.CharField(max_length=50)),
                ('num_ques_solved', models.IntegerField(default=0)),
                ('num_ques_att', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
